### ISSUE TITLE
CNN Face Detector Accuracy

### ISSUE THREAD

**Issue by jamessmith90** [symisc/sod#12]
Hi,

Before buying the model i just want to check the accuracy on my own dataset.

Q1. Does it work on linux ?
Q2. If you can share an .exe with a parameter as path of the video file i will check the accuracy.

Thanks.

**Comment by symisc** [comment]
@jamessmith90 

1. All models are cross-platform and works on any system (i.e. Windows, Linux, BSDs, Android, iOS, etc.) where SOD compiles.
2. The CNN face model accuracy is around 85.5 mAP which mean that you'll be able to catch faces at different scales & shapes (i.e. frontal, inclined, large, tiny, etc.) easily under different conditions.
3. You can download this Windows program for Facial Landmarks extraction demo although it uses the SOD Realnets for frontal face detection which is less robust than the CNN model you plan to purchase : https://sod.s3.amazonaws.com/face_landmarks.rar.

**Comment by jamessmith90** [comment]
@symisc 
Thanks for replying.
This demo works on webcam only and i want to test it my own videos.
Kindly update.

**Comment by symisc** [comment]
@jamessmith90 
There is no such demo. It is up to you to deploy & test the model on your own video stream and dataset.
 
As said earlier, the CNN face detector is one of the robust model out there. It should detect any face without issue giving a good quality image/video frame.

**Comment by jamessmith90** [comment]
@symisc 
Fine ! Lets do it other way.
What is the F1 score of your CNN detector on wider face dataset ?

**Comment by symisc** [comment]
The model was trained on the GENKI-4K and a proprietary dataset. As said earlier, it has an mAP of 85.5.

**Comment by jamessmith90** [comment]
This will only work on webcam. I am looking for something that can work on 4K videos with a distance of 20 meters.

**Comment by symisc** [comment]
Absolutely not, the _Realnet frontal face detector_ is designed to work mostly with Webcams and phone frontal camera. The **CNN face detector** you are talking about fits perfectly for external environments like CCTV camera stream and so forth especially 4K videos. You can shot an email to PixLab at _support [at] pixlab.io_ if you need further information.
