### ISSUE TITLE
Bugs found in function "canny_non_max_suppression"

### ISSUE THREAD

**Issue by jfzcoman** [symisc/sod#19]
"if (g[x + y] > g[x + y - w] && g[x + y] > g[x + y + w])"(line 10532 in sod.c),segment fault with x+y equal to 0 .

**Comment by symisc** [comment]
This is a know issue in the canny edge detection algorithm as reported first from the issue:https://github.com/symisc/sod/issues/16. Could you share the C code that triggered the SEGFAULT?

**Comment by jfzcoman** [comment]
It must g[x+y-w] access data out of image,so I make a slight modification in "sod_canny_edge_image"(line 10813 in sod.c) with following(line 10827)
g = malloc(im.w *( im.h+1) * sizeof(int));
dir = malloc(im.w *( im.h+1) * sizeof(int));
if (g && dir && sobel.data && out.data) {
canny_calc_gradient_sobel(&clean, &g[im.w], &dir[im.w]);
canny_non_max_suppression(&sobel, &g[im.w], &dir[im.w]);
canny_estimate_threshold(&sobel, &high, &low);
canny_hysteresis(high, low, &sobel, &out);
}

**Comment by jfzcoman** [comment]
plus "g[x + y + w]" will access data outside of image,so
g = malloc(im.w *( im.h+2) * sizeof(int));
dir = malloc(im.w *( im.h+2) * sizeof(int));
would be fine,right?

**Comment by symisc** [comment]
Try the following and report back (I'm guessing you're running SOD on a intel 64 bit system):
```C
	g = malloc(im.w *(im.h + 16) * sizeof(int));
	dir = malloc(im.w *(im.h + 16) * sizeof(int));
	if (g && dir && sobel.data && out.data) {
		canny_calc_gradient_sobel(&clean, &g[im.w], &dir[im.w]);
		canny_non_max_suppression(&sobel, &g[im.w], &dir[im.w]);
		canny_estimate_threshold(&sobel, &high, &low);
		canny_hysteresis(high, low, &sobel, &out);
	}
```
Thanks

**Comment by jfzcoman** [comment]
Thanks,it worked,I'm using mingw32 and Windows7. but why `im.h+16`?

**Comment by symisc** [comment]
@jfzcoman Bytes alignment...Intel CPU are weird sometimes..

**Comment by jfzcoman** [comment]
But I thank by adding 16 is adding 16 lines to the image.and that cost more memory

**Comment by symisc** [comment]
It does not add anything to the image, only cost few more memory bytes. The final image output (canny edged) is stored in `sod_img out;` which has exactly the same **width** & **height** as the input image.

**Comment by jfzcoman** [comment]
Yes,I meant the g and dir have more 16 lines than the source image.

**Comment by symisc** [comment]
Make sure to update to the latest version of SOD which fix the canny edge memory leak https://sod.pixlab.io/changelog.html
