### ISSUE TITLE
how to train realnet face detection

### ISSUE THREAD

**Issue by syedmustafa54** [symisc/sod#20]
I want to train realnet face detection I have downloaded genki4k data set want to train the model and test the accuracy but this [pedestrian detector](https://sod.pixlab.io/c_api/sod_realnet_train_start.html) is looking as object classification not object detection for face detection its object detection so how can i train objection on real net 
what I mean is I have trained many object detection and everyone requires object coordinates (means bounding box, lable image) but on this tutorial there is nothing like this.

**Comment by symisc** [comment]
The face detection model is already available to download from https://pixlab.io/downloads. If you plan to train a single class such as pedestrian, car, dog, etc., then there is no need for a GPU version, the Realnet training interfaces (https://sod.pixlab.io/api.html#sod_realnet_trainer) should do the work for you. Do not ask for tutorials here, please read the documentation first.
