### ISSUE TITLE
About pre-trained modules

### ISSUE THREAD

**Issue by henrysh28** [symisc/sod#22]
I just failed to access the download page of pre-trained modules (url like pixlab.io/download), anybody could help me ?

**Comment by symisc** [comment]
The models download page is located at https://pixlab.io/downloads

**Comment by henrysh28** [comment]
Thanks a lot for your reply,  I reviewed the pixlab.io/downloads <http://pixlab.io/downloads> page and found it empty.
Any other ways?
:)

Best regards

**Comment by ctsrc** [comment]
@henrysh28 is JavaScript enabled in your browser? Are you using any browser extensions that are blocking scripts from loading, like for example NoScript or uMatrix?

With JavaScript disabled, the page in question will appear to be empty.

With JavaScript enabled, the download links are there.

**Comment by symisc** [comment]
@ctsrc  Issue has been resolved for this user. Thanks for your assistance.
