### ISSUE TITLE
Target HW

### ISSUE THREAD

**Issue by yldzmuhammed** [symisc/sod#23]
Hello everyone,

Firstly great thanks for work. And second, 

What exactly sod is?

**Comment by symisc** [comment]
Hi Muhammed,

SOD is an embedded computer vision and machine learning software library similar to OpenCV and it exposes a set of APIs for deep-learning, advanced media analysis & processing including real-time, multi-class object detection and model training on embedded systems with limited computational resource and IoT devices. Find out more at https://sod.pixlab.io
