### ISSUE TITLE
About disable SSE2 

### ISSUE THREAD

**Issue by 123toorc** [symisc/sod#28]
Hi, 
    I'm working on the project that is going to integrate the sod as a benchmark. Unfortunately, we are blocked at the compilation stage, our environment set up let us we can't support SSE2. We have plenty of error regarding: 
for example:
`
    always_inline function '_mm_load_si128' requires target feature 'sse2', but would be inlined into function 'stbi__idct_simd' that is compiled without support for 'sse2'
`
is that possible there is some alternative function as _mm_load_si128 _mm_set1_epi32 _mm_set1_epi16, etc. It is inside the sod_img_reader.h.

**Comment by symisc** [comment]
On x86, SSE2 will automatically be used when available based on a run-time test; if not, the generic C versions are used as a fall-back. 
If for some reason you do not want to use any of SIMD code, or if you have issues compiling it, you can disable it entirely by defining **STBI_NO_SIMD**.
