### ISSUE TITLE
Possible to use RealNets for object detection?

### ISSUE THREAD

**Issue by KurtKoo** [symisc/sod#29]
Is it possible to use RealNets for object detection as sod_cnn interfaces do?

for example:
Train a model like "tiny20.sod" using sod_trainning interfaces.

And the model is used in sod_realnet_detect for 20-class object detection & classification.

**Comment by symisc** [comment]
Realnets are single class detectors only. But, since there are very fast, you can stackup multiple detector (eg. pedestrian, car, tree) on top of each others via successive calls to [sod_realnet_load_model_from_disk](https://sod.pixlab.io/c_api/sod_realnet_load_model_from_disk.html)

**Comment by KurtKoo** [comment]
> Realnets are single class detectors only. But, since there are very fast, you can stackup multiple detector (eg. pedestrian, car, tree) on top of each others via successive calls to [sod_realnet_load_model_from_disk](https://sod.pixlab.io/c_api/sod_realnet_load_model_from_disk.html)

Helpful suggestion.

Thank you!
