### ISSUE TITLE
realnet_train_model

### ISSUE THREAD

**Issue by qaz734913414** [symisc/sod#3]
Parsing done. Processing network layers now..

Processing layer: 'paths'..

Processing layer: 'detector'..

Collecting positive samples..

Entering directory: 'pedestrian_dataset/positives'..

Over 300 positive samples were collected so far..

Over 600 positive samples were collected so far..

Over 900 positive samples were collected so far..

Over 1200 positive samples were collected so far..

Over 1500 positive samples were collected so far..

Over 1800 positive samples were collected so far..

Over 2100 positive samples were collected so far..

Over 2400 positive samples were collected so far..

Over 2700 positive samples were collected so far..

2908 positive samples were collected on directory: 'pedestrian_dataset/positives'

Collecting negative samples..

IO error while entering directory: 'pedestrian_dataset/background'

**Comment by symisc** [comment]
This error mean that the negative samples path ('pedestrian_dataset') is invalid. Either you uncomment it with a # or put a valid path where background images (i.e anything but a pedestrian images) can be collected.



-----Original Message-----
