### ISSUE TITLE
On https://sod.pixlab.io/ "that expose" should be "that exposes"

### ISSUE THREAD

**Issue by shlomif** [symisc/sod#32]
On https://sod.pixlab.io/ and https://github.com/symisc/sod/ :

«
SOD is an embedded, modern cross-platform computer vision and machine learning software library that expose[should be "that exposes"] a set of APIs for deep-learning, advanced media analysis & processing including real-time, multi-class object detection and model training on embedded systems with limited computational resource and IoT devices.
»

**Comment by symisc** [comment]
Thanks for this wonderful contribution @shlomif!

**Comment by shlomif** [comment]
@symisc : you're welcome - and thanks.
