### ISSUE TITLE
The problem of training samples

### ISSUE THREAD

**Issue by qaz734913414** [symisc/sod#5]
What are the requirements of the SOD training model for samples? How do we deal with the positive and negative samples? Are there any restrictions on the size and so on?

**Comment by symisc** [comment]
SOD itself with its exported training interfaces does not impose any restrictions on the model you are going to train. The only restriction is how large is your dataset (The larger the dataset is, the more accurate your model) and the amount of RAM, CPU power on the host computer.

**Comment by symisc** [comment]
This is a hint and no way an error. Two possibility you are facing off:
1. The negative samples you provided are too small and the cascade is overfitting. It will perform very well on this set but will not generalise on an unknown image set. Provide a larger dataset to fix the issue.
2. As the message said. Your model perform very well and it's time to stop training and start testing your model in the wild.

-----Original Message-----
