### ISSUE TITLE
Liveness detection model and sample example code for using Face as authentication mechanism on mobiles

### ISSUE THREAD

**Issue by bvananda** [symisc/sod#7]
We are a mobile OEM company, want to use Face based authentication for unlocking the phone.   As of now you have only Face detection and recognition examples, We need Liveness detection models and sample code as well.

**Comment by symisc** [comment]
You can download and try this Windows desktop demo of facial landmarks extraction that you can use in your future work. The facial landmarks model is available at the SOD [download page](https://pixlab.io/downloads).

Windows Desktop Facial Landmarks demo: https://sod.s3.amazonaws.com/face_landmarks.rar

**Comment by symisc** [comment]
A face recognition and a facial landmarks extractor models should handle this task easily. All the rest is just standard programming.
We do offer bespoke development if you want this to be developed for you. Contact support@pixlab.io for additional information.


-----Original Message-----
