### ISSUE TITLE
SOD Model unable to open

### ISSUE THREAD

**Issue by JaccoVeldscholten** [symisc/sod#8]
Getting error when running Face detection.

"Cannot open SOD model"

It is not described what this error means and how to solve it. Would be great to know.
```

`CC = clang
CFLAGS = -lm -Ofast -march=native -Wall -std=c99

sod: sod.c
	$(CC) sod.c samples/cnn_face_detection.c -o sod_face_detect -I. $(CFLAGS)`
```

**Comment by symisc** [comment]
You need to [download](https://pixlab.io/downloads) the target model first or [train your own](https://sod.pixlab.io/c_api/sod_realnet_train_start.html) in order to perform face or object detection. Once done, you pass the model disk path to the target interface to start the detection process
